# A/B Testing from Scratch: Multi-armed Bandits

In [1]:
import numpy as np
import pandas as pd

#widgets
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from IPython.display import display

#plots
import matplotlib.pyplot as plt
from plotnine import *

#stats
import scipy as sp
import statsmodels as sm

In [217]:
class Arm:
    def __init__(self,true_p):
        self.true_p = true_p
        self.reset()
    def reset(self):
        self.impressions = 0
        self.actions = 0
    def get_state(self):
        return self.impressions,self.actions
    def get_rate(self):
        return self.actions / self.impressions
    def pull(self):
        self.impressions+=1
        res = 1 if np.random.random() < self.true_p else 0
        self.actions+=res
        return res
a = Arm(0.1)
for i in range(100): a.pull()
a.get_state()

(100, 16)

In [218]:
class MusketeerEnv:
    def __init__(self, true_ps, avg_impressions):
        self.true_ps = true_ps
        self.avg_impressions = avg_impressions
        self.nb_arms = len(true_ps)
        self.reset()
    def reset(self):
        self.t = -1
        self.ds=[]
        self.arms = [Arm(p) for p in self.true_ps]
        return self.get_state()
    def get_state(self):
        return [self.arms[i].get_state() for i in range(self.nb_arms)]
    def get_impressions(self):
        return int(np.random.triangular(self.avg_impressions/2,
                                    self.avg_impressions,
                                    self.avg_impressions*1.5))
    def step(self, ps):
        self.t+=1
        impressions = self.get_impressions()
        for i in np.random.choice(a=self.nb_arms,size=impressions,p=ps):
            self.arms[i].pull()
        self.record()
        return self.get_state()
    def record(self):
        d = {'t':self.t,'max_rate':0,'opt_impressions':0}
        for i in range(self.nb_arms):
            d[f'impressions_{i}'],d[f'actions_{i}'] = self.arms[i].get_state()
            d[f'rate_{i}'] = d[f'actions_{i}'] / d[f'impressions_{i}']
            if d[f'rate_{i}'] > d['max_rate']: 
                d['max_rate'] = d[f'rate_{i}']
                d['opt_impressions'] = d[f'impressions_{i}']
        d['total_impressions'] = sum([self.arms[i].impressions for i in range(self.nb_arms)])
        d['opt_impressions_rate'] = d['opt_impressions'] / d['total_impressions']
        d['total_actions'] = sum([self.arms[i].actions for i in range(self.nb_arms)])
        d['total_rate'] = d['total_actions'] / d['total_impressions']
        d['regret_rate'] = d['max_rate'] - d['total_rate']
        d['regret'] = d['regret_rate'] * d['total_impressions']
        self.ds.append(d)
    def show_df(self):
        df = pd.DataFrame(self.ds)
        cols = ['t'] + [f'rate_{i}' for i in range(self.nb_arms)]+ \
               [f'impressions_{i}' for i in range(self.nb_arms)]+ \
               [f'actions_{i}' for i in range(self.nb_arms)]+ \
               ['total_impressions','total_actions','total_rate']+ \
               ['regret_rate','regret']+ \
               ['opt_impressions','opt_impressions_rate']
        df = df[cols]
        return df
env = MusketeerEnv(true_ps = [0.1,0.12,0.13], avg_impressions=500)

In [219]:
for i in range(10):
    print(env.step([0.7,0.2,0.1]))

[(430, 40), (149, 15), (76, 10)]
[(748, 70), (254, 28), (119, 14)]
[(1141, 117), (359, 43), (164, 19)]
[(1605, 162), (504, 62), (226, 25)]
[(1890, 186), (583, 73), (258, 32)]
[(2300, 243), (706, 85), (310, 38)]
[(2693, 272), (820, 102), (363, 47)]
[(3046, 305), (919, 116), (426, 54)]
[(3365, 335), (1012, 127), (472, 65)]
[(3714, 373), (1123, 145), (529, 77)]


In [225]:
env.show_df()

t    rate_0    rate_1    rate_2  impressions_0  impressions_1  \
0    0  0.169811  0.119048  0.131661             53             42   
1    1  0.112150  0.117647  0.112994            107            102   
2    2  0.125000  0.130137  0.111992            136            146   
3    3  0.112613  0.138889  0.115385            222            216   
4    4  0.114695  0.133829  0.117021            279            269   
5    5  0.107463  0.148867  0.120682            335            309   
6    6  0.102564  0.146552  0.125716            390            348   
7    7  0.105618  0.145038  0.124304            445            393   
8    8  0.102510  0.144186  0.123826            478            430   
9    9  0.097928  0.141649  0.123869            531            473   
10  10  0.099485  0.154426  0.125887            583            531   
11  11  0.100154  0.152941  0.124790            649            595   
12  12  0.094556  0.156297  0.124811            698            659   
13  13  0.093176  0.150273  0.126792            762            732   
14  14  0.095238  0.145594  0.127717            798            783   
15  15  0.094498  0.142174  0.127660            836            837   
16  16  0.095672  0.138603  0.129283            878            873   
17  17  0.094380  0.138710  0.130188            943            930   
18  18  0.098704  0.135438  0.131606           1003            982   
19  19  0.099720  0.134158  0.132351           1073           1051   
20  20  0.102902  0.133155  0.132200           1137           1119   
21  21  0.101437  0.133851  0.132416           1183           1158   
22  22  0.101723  0.131601  0.131432           1219           1193   
23  23  0.104216  0.133117  0.131372           1257           1232   
24  24  0.104814  0.131393  0.131019           1288           1271   
25  25  0.105105  0.132263  0.130414           1332           1308   
26  26  0.104810  0.130979  0.129351           1393           1359   
27  27  0.103616  0.131299  0.128423           1438           1409   
28  28  0.105440  0.130137  0.128432           1489           1460   
29  29  0.105263  0.132546  0.128813           1539           1524   
..  ..       ...       ...       ...            ...            ...   
70  70  0.099468  0.124217  0.130040           3569           3510   
71  71  0.098564  0.123342  0.130108           3622           3543   
72  72  0.099293  0.123817  0.130007           3676           3594   
73  73  0.099222  0.123153  0.130050           3729           3654   
74  74  0.099149  0.122769  0.129882           3762           3698   
75  75  0.099023  0.123060  0.129793           3787           3738   
76  76  0.098566  0.122714  0.129571           3835           3773   
77  77  0.099131  0.122263  0.129322           3914           3836   
78  78  0.099698  0.121876  0.129809           3972           3881   
79  79  0.099453  0.122038  0.130188           4022           3925   
80  80  0.099828  0.121724  0.130021           4067           3968   
81  81  0.099222  0.121477  0.130001           4112           4009   
82  82  0.098487  0.122439  0.130199           4163           4051   
83  83  0.098885  0.121390  0.130154           4217           4086   
84  84  0.098499  0.121425  0.129939           4264           4126   
85  85  0.099329  0.120900  0.130231           4319           4177   
86  86  0.099564  0.121327  0.130080           4359           4220   
87  87  0.099271  0.120779  0.130085           4392           4264   
88  88  0.099461  0.121205  0.130112           4454           4315   
89  89  0.099489  0.120934  0.130183           4503           4366   
90  90  0.099496  0.120979  0.130004           4563           4414   
91  91  0.100087  0.121837  0.129763           4606           4465   
92  92  0.100494  0.122124  0.129542           4657           4520   
93  93  0.099979  0.122520  0.129771           4731           4587   
94  94  0.100188  0.123249  0.129740           4791           4641   
95  95  0.10037

In [221]:
class Agent:
    def __init__(self, env):
        self.env = env
    def equal_weights(self):
        res = np.array([1/self.env.nb_arms for i in range(self.env.nb_arms)])
        return res
    def randomize(self):
        res = np.random.rand(self.env.nb_arms)
        res /= res.sum()
        return res
    def greedy(self):
        res = np.array([0 for i in range(self.env.nb_arms)])
        best_idx = np.argmax([self.env.arms[i].get_rate() for i in range(self.env.nb_arms)])
        res[best_idx] = 1
        return res
    def eps_greedy(self, eps = 0.3):
        res = np.array([eps/self.env.nb_arms for i in range(self.env.nb_arms)])
        best_idx = np.argmax([self.env.arms[i].get_rate() for i in range(self.env.nb_arms)])
        res[best_idx] += 1-eps
        return res
    def softmax(self,tau=0.05):
        sum_exp = sum([np.exp(env.arms[i].get_rate()/tau) for i in range(self.env.nb_arms)])
        res = np.array([np.exp(env.arms[i].get_rate()/tau) / sum_exp for i in range(self.env.nb_arms)])
        return res
    def ucb(self):
        ucbs = [self.env.arms[i].get_rate() + np.sqrt()]
    def thompson(self):
        pass

a = Agent(env)
a.equal_weights(), a.randomize(), a.greedy(), a.eps_greedy(), a.softmax()

(array([0.33333333, 0.33333333, 0.33333333]),
 array([0.45814235, 0.50189778, 0.03995987]),
 array([0, 0, 1]),
 array([0.1, 0.1, 0.8]),
 array([0.19081179, 0.33867473, 0.47051348]))

In [222]:
[env.arms[i].get_rate() for i in range(env.nb_arms)]

[0.10043080236941303, 0.12911843276936777, 0.14555765595463138]

In [223]:
env = MusketeerEnv(true_ps = [0.1,0.12,0.13], avg_impressions=500)
for i in range(100):
    action = a.eps_greedy()
    env.step(action)

In [224]:
np.random.rand(10)

array([0.22921063, 0.25874669, 0.49074226, 0.41564119, 0.86889909,
       0.31964825, 0.83444461, 0.75162391, 0.77964637, 0.84843834])